/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.9/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "algo"

plugins {
//    id("java")
}

// list folders in current dir
val folders = File(".").listFiles()?.filter { it.isDirectory && !it.name.startsWith(".") && !it.name.equals("buildSrc") }

// include all folders as subprojects
folders?.forEach { folder ->
    include(folder.name)
}

